### ISSUE TITLE
创建多条记录时报错

### ISSUE THREAD

**Issue by wantsget** [donjan-deng/hyperf-permission#12]
hyperf版本 v2.0.16

```
$permission = Permission::create(['name' => 'user-center/user/get','display_name'=>'用户管理','url'=>'user-center/user']);
$permission = Permission::create(['name' => 'user-center/user/post','display_name'=>'创建用户','parent_id'=>$p1->id]);
```

按照该方法创建多条记录时，报错
```
PHP Fatal error:  Uncaught Error: Class 'Hyperf\Database\Model\Relations\Relation' not found in /hyperf-all/vendor/hyperf/database/src/Model/Builder.php:625
Stack trace:
#0 /hyperf-all/vendor/hyperf/database/src/Model/Builder.php(1104): Hyperf\Database\Model\Builder->getRelation('roles')
#1 /hyperf-all/vendor/hyperf/database/src/Model/Builder.php(607): Hyperf\Database\Model\Builder->eagerLoadRelation(Array, 'roles', Object(Closure))
#2 /hyperf-all/vendor/hyperf/database/src/Model/Builder.php(576): Hyperf\Database\Model\Builder->eagerLoadRelations(Array)
#3 /hyperf-all/vendor/donjan-deng/hyperf-permission/src/PermissionRegistrar.php(93): Hyperf\Database\Model\Builder->get()
#4 /hyperf-all/vendor/donjan-deng/hyperf-permission/src/Models/Permission.php(147): Donjan\Permission\PermissionRegistrar->getPermissions(Array)
#5 /hyperf-all/vendor/donjan-deng/hyperf-permission/src/Models/Permission.php(41): Donjan\Permission\Models\Permission::getPermissions(Array)
#6 /hyperf-all/app/Command/PermissionCommand.php(60): Donjan\Permission\M in /hyperf-all/vendor/hyperf/database/src/Model/Builder.php on line 625
```

看了下源码，Donjan\Permission\Models\Permission.php中的create方法有这一行
```
$permission = static::getPermissions(['name' => $attributes['name'], 'guard_name' => $attributes['guard_name']])->first();
```

只要注释掉这个，就能通过。

请问如果要初始化数据的话，用什么方式好呢？

比如要创建父子级权限：

|- user
     |- user-xxx
     |- user-xxx1

**Comment by donjan-deng** [comment]
可以创建多条记录，$p哪儿来的？如果是你代码运行出错中断，会存在缓存问题，先执行`php bin/hyperf.php permission:cache-reset`清除缓存

**Comment by wantsget** [comment]
不好意思啊，我最开始的代码没有上全。

我之前想写一个Command来实现truncate数据表然后写入新的权限数据，当我使用Donjan\Permission\Models\Permission类来创建多个父子级权限时出现了以上报错。

后来我就参考您的la-user-center项目，换成了Seeder来填充数据。
-------------------------------------------

关于$p1其实是这样的

```
// 先创建一个父级权限，因为我看创建时没有传递该条记录的主键id，于是打算拿$p1->id来取父权限的id
$p1 = Permission::create(['name' => 'user-center/user/get','display_name'=>'用户管理','url'=>'user-center/user']);
// 然后第二行这里 想用$p1->id来赋值，就报错了
$permission = Permission::create(['name' => 'user-center/user/post','display_name'=>'创建用户','parent_id'=>$p1->id]);
```

**Comment by donjan-deng** [comment]
测试没问题的，你估计是有错误的缓存，运行php bin/hyperf.php permission:cache-reset把错误的缓存清除了
